import axios from 'axios';

export const fetchShow = () => {
    return axios
    .get("https://api.tvmaze.com/singlesearch/shows?q=stranger-things&embed=episodes")
    .then(res => {
        console.log("This is the fetchShow response", res);
        return res;
    })
    .catch( err => {
        console.log("Error generated by fetchShow API Component: ", err);
        return err;
    });
};