import React from 'react'
import { render, screen} from '@testing-library/react'
import Episodes from './Episodes'


//without the props passed, we are getting an error taht says "cannot read property 'map' of undefined"
//why are we seeing this error in our test and not in the UI?
// because in our component we passed an array down as a prop, in our test we didn't pass anything down. 
// we need to pass down the prop with an empty array to make it so the test runs. (A required prop)
test('render to check if rendering', () => {
    render(<Episodes episodes={[]}/>)
})

const episodesData = [{id:2993,url:"https://www.tvmaze.com/shows/2993/stranger-things",name:"Stranger Things",type:"Scripted",language:"English",genres:["Drama","Fantasy","Science-Fiction"],status:"Running",runtime:60,premiered:"2016-07-15",officialSite:"https://www.netflix.com/title/80057281",schedule:{time:"",days:[]},rating:{average:8.7},weight:98,network:null,webChannel:{id:1,name:"Netflix",country:null},externals:{tvrage:48493,thetvdb:305288,imdb:"tt4574334"},image:{medium:"https://static.tvmaze.com/uploads/images/medium_portrait/200/501942.jpg",original:"https://static.tvmaze.com/uploads/images/original_untouched/200/501942.jpg"},summary:"<p>A love letter to the '80s classics that captivated a generation, <b>Stranger Things</b> is set in 1983 Indiana, where a young boy vanishes into thin air. As friends, family and local police search for answers, they are drawn into an extraordinary mystery involving top-secret government experiments, terrifying supernatural forces and one very strange little girl.</p>",updated:1604039949,_links:{self:{href:"https://api.tvmaze.com/shows/2993"},previousepisode:{href:"https://api.tvmaze.com/episodes/1576476"}},_embedded:{episodes:[{id:553946,url:"https://www.tvmaze.com/episodes/553946/stranger-things-1x01-chapter-one-the-vanishing-of-will-byers",name:"Chapter One: The Vanishing of Will Byers",season:1,number:1,type:"regular",airdate:"2016-07-15",airtime:"",airstamp:"2016-07-15T12:00:00+00:00",runtime:60,image:{medium:"https://static.tvmaze.com/uploads/images/medium_landscape/67/168918.jpg",original:"https://static.tvmaze.com/uploads/images/original_untouched/67/168918.jpg"},summary:"<p>A young boy mysteriously disappears, and his panicked mother demands that the police find him. Meanwhile, the boy's friends conduct their own search, and meet a mysterious girl in the forest.</p>",_links:{self:{href:"https://api.tvmaze.com/episodes/553946"}}},
{id:578663,url:"https://www.tvmaze.com/episodes/578663/stranger-things-1x02-chapter-two-the-weirdo-on-maple-street",name:"Chapter Two: The Weirdo on Maple Street",season:1,number:2,type:"regular",airdate:"2016-07-15",airtime:"",airstamp:"2016-07-15T12:00:00+00:00",runtime:60,image:{medium:"https://static.tvmaze.com/uploads/images/medium_landscape/72/181376.jpg",original:"https://static.tvmaze.com/uploads/images/original_untouched/72/181376.jpg"},summary:"<p>While the search for the missing Will continues, Joyce tells Jim about a call she apparently received from her son. Meanwhile, Jane warns Mike that there are bad people after her, and he realizes that she knows what happened to Will.</p>",_links:{self:{href:"https://api.tvmaze.com/episodes/578663"}}},{id:578664,url:"https://www.tvmaze.com/episodes/578664/stranger-things-1x03-chapter-three-holly-jolly",name:"Chapter Three: Holly, Jolly",season:1,number:3,type:"regular",airdate:"2016-07-15",airtime:"",airstamp:"2016-07-15T12:00:00+00:00",runtime:60,image:{medium:"https://static.tvmaze.com/uploads/images/medium_landscape/67/168920.jpg",original:"https://static.tvmaze.com/uploads/images/original_untouched/67/168920.jpg"},summary:"<p>While Nancy looks for a missing Barbara and realizes that Jonathan may have been the last person to see her, Mike and his friends go out with Jane to find the missing Will. Meanwhile, Jim tracks Will to the lab.</p>",_links:{self:{href:"https://api.tvmaze.com/episodes/578664"}}},{id:578665,url:"https://www.tvmaze.com/episodes/578665/stranger-things-1x04-chapter-four-the-body",name:"Chapter Four: The Body",season:1,number:4,type:"regular",airdate:"2016-07-15",airtime:"",airstamp:"2016-07-15T12:00:00+00:00",runtime:60,image:{medium:"https://static.tvmaze.com/uploads/images/medium_landscape/67/168921.jpg",original:"https://static.tvmaze.com/uploads/images/original_untouched/67/168921.jpg"},summary:"<p>Jim realizes that the government is covering something up about Will's death and begins a personal investigation. Meanwhile, Nancy discovers that Jonathan has information about Barbara's disappearance, while Mike and his friends smuggle Jane into the school so she can use the ham radio to contact Will.</p>",_links:{self:{href:"https://api.tvmaze.com/episodes/578665"}}},
{id:578666,url:"https://www.tvmaze.com/episodes/578666/stranger-things-1x05-chapter-five-the-flea-and-the-acrobat",name:"Chapter Five: The Flea and the Acrobat",season:1,number:5,type:"regular",airdate:"2016-07-15",airtime:"",airstamp:"2016-07-15T12:00:00+00:00",runtime:60,image:{medium:"https://static.tvmaze.com/uploads/images/medium_landscape/67/168922.jpg",original:"https://static.tvmaze.com/uploads/images/original_untouched/67/168922.jpg"},summary:"<p>Jim searches for Will at Hawkins Laboratory, but finds something unexpected. Meanwhile, Lonnie helps Joyce bury Will but reveals an ulterior motive for returning to town, while the boys find a way to locate Will but discover that Jane is opposing them.</p>",_links:{self:{href:"https://api.tvmaze.com/episodes/578666"}}},{id:578667,url:"https://www.tvmaze.com/episodes/578667/stranger-things-1x06-chapter-six-the-monster",name:"Chapter Six: The Monster",season:1,number:6,type:"regular",airdate:"2016-07-15",airtime:"",airstamp:"2016-07-15T12:00:00+00:00",runtime:60,image:{medium:"https://static.tvmaze.com/uploads/images/medium_landscape/67/168923.jpg",original:"https://static.tvmaze.com/uploads/images/original_untouched/67/168923.jpg"},summary:"<p>Jonathan manages to pull Nancy back to the real world from the Upside Down. Meanwhile, Lucas refuses to help with the search for Jane and goes to Hawkins Labs on his own, while Dustin and Mike look for the missing girl.</p>",_links:{self:{href:"https://api.tvmaze.com/episodes/578667"}}},{id:578668,url:"https://www.tvmaze.com/episodes/578668/stranger-things-1x07-chapter-seven-the-bathtub",name:"Chapter Seven: The Bathtub",season:1,number:7,type:"regular",airdate:"2016-07-15",airtime:"",airstamp:"2016-07-15T12:00:00+00:00",runtime:60,image:{medium:"https://static.tvmaze.com/uploads/images/medium_landscape/67/168925.jpg",original:"https://static.tvmaze.com/uploads/images/original_untouched/67/168925.jpg"},summary:"<p>Jim manages to bring everyone together so that they can join forces to reconnect Jane to the Upside Down and find Will. Meanwhile, the government closes in on Jane and the boys.</p>",_links:{self:{href:"https://api.tvmaze.com/episodes/578668"}}},
]}}];


// we are going to pretend that our user clicks on the buttons to select an episode, and then the props
// inside our data changes.
test('re-render properly with episodes data', ()=>{
        // render(<Episodes episodes={[]}/>)
            // above we will want to deconstruct rerender from our render func. This is destructuring off of the container object. like so...
    const {rerender} = render(<Episodes episodes={[]}/>)
        //this allows us to rerender our component and mock/pretend that props or state has changed.

    //first assert there are no episodes in the UI
    //use .not.toBeNull() as a sanity check if not.toBeNull, then it should fail.
    expect(screen.queryByText(/Season 1, Episode 1/i)).toBeNull();
    
    //re-render the component with new props
        rerender(<Episodes episodes={episodesData}/>)

    //assert that missions are rendered in UI. 
})

